name: Auto-merge

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

env:
  MY_REPO: https://ClusterM:${{secrets.GITHUB_TOKEN}}@github.com/ClusterM/fceux.git
  MY_BRANCH: coolgirl
  MASTER_REPO: https://github.com/TASVideos/fceux.git
  MASTER_BRANCH: master

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge with the master
      run: |
        git clone ${{env.MY_REPO}} -b ${{env.MY_BRANCH}} tmp
        cd tmp
        OLD_COMMIT=$(git rev-parse HEAD)
        git config user.name "Automerge Bot"
        git config user.email "bot@example.com"
        git config pull.rebase false        
        git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
        NEW_COMMIT=$(git rev-parse HEAD)
        git push
        if [ "$OLD_COMMIT" != "$NEW_COMMIT" ]
        then
          echo "Successfully merged with master branch"
          echo "New commit: $NEW_COMMIT"
          echo "Lets send rebuild request!"
          OUTPUT=$(curl -s -X POST https://api.github.com/repos/ClusterM/fceux/dispatches -H 'Accept: application/vnd.github.everest-preview+json' -u ${{secrets.DISPATCH_KEY}} --data '{"event_type": "Automerge-rebuild"}')
          if [ ! -z "$OUTPUT" ]
          then
            echo "::error curl output: $OUTPUT"
            exit 1
          fi
        else
          echo "::warning::Everything already up to date"
        fi
