name: Automerge

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

env:
  MASTER_REPO: https://github.com/TASVideos/fceux.git
  MASTER_BRANCH: master

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Debug
      run: |
        git status
        git branch
        git log

    - name: Merge with master
      run: |
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
        git push
