name: WinX86

on:
  push:
    branches: [ coolgirl ]
  pull_request:
    branches: [ coolgirl ]
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: vc/vc14_fceux.vcxproj
  BUILD_CONFIGURATION: Release
  PLATFORM: Win32
  OUTPUT_FILE: fceux.zip
  OUTPUT_SUBDIRECTORY: fceux

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: msbuild ${{env.SOLUTION_FILE_PATH}} /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.PLATFORM}}

    - name: Archive
      working-directory: output
      run: |
        mkdir ${{env.OUTPUT_SUBDIRECTORY}}
        move palettes ${{env.OUTPUT_SUBDIRECTORY}}
        move luaScripts ${{env.OUTPUT_SUBDIRECTORY}}
        move tools ${{env.OUTPUT_SUBDIRECTORY}}
        move fceux.exe ${{env.OUTPUT_SUBDIRECTORY}}
        move lua5.1.dll ${{env.OUTPUT_SUBDIRECTORY}}
        move lua51.dll ${{env.OUTPUT_SUBDIRECTORY}}
        move auxlib.lua ${{env.OUTPUT_SUBDIRECTORY}}
        move 7z.dll ${{env.OUTPUT_SUBDIRECTORY}}
        move fceux.chm ${{env.OUTPUT_SUBDIRECTORY}}
        move taseditor.chm ${{env.OUTPUT_SUBDIRECTORY}}
        ..\vc\zip -X -9 -r ${{env.OUTPUT_FILE}} ${{env.OUTPUT_SUBDIRECTORY}}

    - uses: actions/upload-artifact@v2
      with:
        name: Windows (x86) build
        path: output/${{env.OUTPUT_FILE}}

    - name: Upload
      if: github.event_name != 'pull_request'
      working-directory: output
      run: curl -F 'file=@${{env.OUTPUT_FILE}}' -F 'key=${{secrets.UPLOADER_KEY}}' '${{secrets.UPLOADER_URL}}'
